### ISSUE TITLE
MAINT: cleanup internal IRSA bucket usage

### ISSUE THREAD

**Issue by bsipocz** [nasa-fornax/fornax-demo-notebooks#311]
- [ ] Spitzer COSMOS Images for the forced photometry notebook (see #121); change to use SEIP from the cloud, or use COSMOS from on-prem. This blocks testing of forced_photometry.md
- [x] #367 . This blocks testing of light_curve_generator.md.
- [x] unWISE data usage for the light curve notebook https://github.com/nasa-fornax/fornax-demo-notebooks/blob/main/light_curves/code_src/wise_functions.py#L104 (#330). This blocks testing of light_curve_generator.md.

**Comment by troyraen** [comment]
Thanks for opening this. I added one more for the unWISE data in light curve notebook.

**Comment by troyraen** [comment]
I have removed the ZTF DR18 Lightcurves from the bucket because the files are no longer usable by our code. See #371. I left the checkbox for ZTF data unchecked above because I am in the process of putting a HATS version of the ZTF DR23 Lightcurves in the testing bucket, so those will need to be cleaned up. Our proposal to get ODR space for ZTF catalogs has been approved, but there will be an interim period during which we'd like to have these files available in this testing bucket before making them publicly available in the ODR bucket.
